spring:
  application:
    name: orderservice
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderservice}
    username: ${DB_USERNAME:alex}
    password: ${DB_PASSWORD:vboris77}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  topics:
    orderNotification: order-notification

server:
  port: 8081
